# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
trigger: none

pool:
  vmImage: 'windows-latest'

steps:
  - task: CredScan@2
    inputs:
      toolMajorVersion: 'V2'

  # - task: Semmle@0
  #   env:
  #     SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  #   inputs:
  #     sourceCodeDirectory: '$(Build.SourcesDirectory)'
  #     language: 'cpp'
  #     querySuite: 'Recommended'
  #     timeout: '1800'
  #     ram: '16384'

  - task: ComponentGovernanceComponentDetection@0
    inputs:
      scanType: 'Register'
      verbosity: 'Verbose'
      alertWarningLevel: 'High'

#  - task: PublishSecurityAnalysisLog@2
#    inputs:
#      ArtifactName: 'CodeAnalysisLogs'
#      ArtifactType: 'Container'
#      AllTools: true
#      ToolLogsNotFoundAction: 'Standard'